### ISSUE TITLE
This problem occurs

### ISSUE THREAD

**Issue by Ckkxx** [HongkunSun/ParaTransCNN#2]
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [208,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [209,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [210,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [211,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [212,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:104: nll_loss2d_forward_kernel: block: [2,0,0], thread: [213,0,0] Assertion `t >= 0 && t < n_classes` failed.

RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by HongkunSun** [comment]
"Hello, the above error should be related to the number of segmentation classes. The correct solution is to adjust the --num_classes parameter, which should be the number of segmentation classes +1."

**Comment by Ckkxx** [comment]
> “您好，上述错误应该与分割类的数量有关。正确的解决方案是调整 --num_classes 参数，该参数应该是分割类的数量 +1。

Thanks, this issue has been resolved, but a new problem arose when using the ResNet model ：
module 'torchvision.models' has no attribute 'ResNet34_Weights'
my python=3.8
torch                     2.2.1                    
torchaudio                0.11.0+cu113           
torchmetrics              1.3.2                   
torchsummary              1.5.1                    
torchvision               0.12.0+cu113

**Comment by HongkunSun** [comment]
"Hello, I have not used Torch version 2.0 or above. You can create a new Python environment to avoid more errors. Please refer to the requirements.txt."

**Comment by Ckkxx** [comment]
> "Hello, I have not used Torch version 2.0 or above. You can create a new Python environment to avoid more errors. Please refer to the requirements.txt."

Thanks for replying, your results in the synapse dataset are not trained multiple times

**Comment by HongkunSun** [comment]
"Hello, I didn't quite understand what you meant. Did you not reproduce my results?"

**Comment by Ckkxx** [comment]
> "Hello, I didn't quite understand what you meant. Did you not reproduce my results?"

Yes, I tried it a few times and my result was: mean_dice: 0.826386

**Comment by HongkunSun** [comment]
"Hello, using different servers (GPU types) may lead to different final results. Thank you very much for your support for our work!"
